### ISSUE TITLE
Test fails during compile

### ISSUE THREAD

**Issue by sebasbaumh** [portfolio-performance/portfolio#4779]
**Describe the bug**
I compile Portfolio version 0.77.2-SNAPSHOT (and also 0.77.1) using this Maven command line:
`mvn -f portfolio-app/pom.xml -Denforcer.skip=true clean verify`

It gives this error:

````
Failures:
  IBFlexStatementExtractorTest.testIBFlexStatementFile18:2669
Expected: an empty collection
     but: <[org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 4488; JAXP00010002:  Element "CashReportCurrency" has more than "200" attributes, "200" is the limit set by "jdk.xml.elementAttributeLimit".]>
  IBFlexStatementExtractorTest.testIBFlexStatementFile19:2872
Expected: an empty collection
     but: <[org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 4396; JAXP00010002:  Element "CashReportCurrency" has more than "200" attributes, "200" is the limit set by "jdk.xml.elementAttributeLimit".]>
  IBFlexStatementExtractorTest.testIBFlexStatementFile21:3112
Expected: an empty collection
     but: <[org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 4568; JAXP00010002:  Element "CashReportCurrency" has more than "200" attributes, "200" is the limit set by "jdk.xml.elementAttributeLimit".]>
  IBFlexStatementExtractorTest.testIBFlexStatementFile22:3198
Expected: an empty collection
     but: <[org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 4488; JAXP00010002:  Element "CashReportCurrency" has more than "200" attributes, "200" is the limit set by "jdk.xml.elementAttributeLimit".]>

Tests run: 3751, Failures: 4, Errors: 0, Skipped: 0
````

**To Reproduce**
1. Check out master branch
2. Execute Maven build using `mvn -f portfolio-app/pom.xml -Denforcer.skip=true clean verify`

**Expected behavior**
Build works without errors in tests.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 0.77.2-SNAPSHOT/0.77.1
